# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bnw6Sn5uR6wrGTgkudD7t2ankR4Maqa8
"""

import pandas as pd
df_heart = pd.read_csv('/content/heart.csv')
display(df_heart.head(5))

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(11,11))
sns.heatmap(df_heart.corr(), annot=True, cmap='coolwarm')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(7,5))
sns.histplot(df_heart['age'], bins=20, kde=True)

plt.title('Age Distribution of Patients', fontsize=14)
plt.xlabel('Age (years)')
plt.ylabel('Frequency')

plt.show()